### ISSUE TITLE
SSL Certificate Problem

### ISSUE THREAD

**Issue by rorymbyrne** [ThreatHuntingProject/hunter#2]
![screen shot 2017-05-09 at 16 09 51](https://cloud.githubusercontent.com/assets/18581795/25857668/b30882fa-34d1-11e7-9a48-726873d7f050.png)

**Comment by DavidJBianco** [comment]
Thanks for pointing this out.  I'm aware that the SSL version of the site uses GitHub's certificate.  Unfortunately, GitHub doesn't seem to support SSL for sites that use their own custom domain names.  I'll keep an eye on this, though, and if they do start to offer this option, I'll see about enabling it.  In the meantime, I recommend simply using the plaintext HTTP version of the site.
